---
# tasks file for /root/.ansible/roles/mycustomrole2
- name: Run Apt Update
  shell: apt update
- name: Clone Git Repo
  shell: cd /tmp && git clone https://github.com/mavrick202/dockertest1.git
  tags:
   - repo
- name: Install Nginx Server
  apt: >
    name=nginx
    state=present
- name: Copy the Index jinja template
  template: >
     src=index.j2
     dest=/var/www/html/index.nginx-debian.html
     owner=root
     group=root
     mode=0644
- name: Copy the style files to destination folder.
  copy: >
     src=/tmp/dockertest1/style.css
     dest=/var/www/html/style.css
     remote_src=yes
     owner=root
     group=root
     mode=0644
- name: Copy the javascript files to destination folder.
  copy: >
     src=/tmp/dockertest1/scorekeeper.js
     dest=/var/www/html/scorekeeper.js
     remote_src=yes
     owner=root
     group=root
     mode=0644
- name: restart nginx
  command: service nginx restart
